"use client";

import { useEffect, useState } from "react";
import { dateMessages, defaultAnswers, match, questions } from "../mock-data";

type Stage = "landing" | "onboarding" | "persona" | "match" | "date" | "report" | "reveal";

function Mark() { return <div className="grid size-9 place-items-center rounded-full border border-violet-200/25 bg-violet-300/10 text-lg text-violet-100">v</div>; }
function Button({ children, onClick, secondary = false, disabled = false }: { children: React.ReactNode; onClick: () => void; secondary?: boolean; disabled?: boolean }) {
  return <button disabled={disabled} onClick={onClick} className={`rounded-full px-6 py-3.5 text-sm font-semibold transition ${secondary ? "border border-white/15 bg-white/5 text-white hover:bg-white/10" : "bg-gradient-to-r from-violet-400 to-fuchsia-300 text-[#170b27] shadow-[0_10px_35px_rgba(181,129,255,.25)] hover:brightness-110 disabled:opacity-50"}`}>{children}</button>;
}
function Shell({ children }: { children: React.ReactNode }) { return <main className="relative min-h-screen overflow-hidden bg-[#0c0715] text-[#f8f4ff]"><div className="pointer-events-none absolute left-[-18rem] top-[-12rem] size-[42rem] rounded-full bg-violet-700/20 blur-3xl" /><div className="pointer-events-none absolute bottom-[-18rem] right-[-16rem] size-[46rem] rounded-full bg-fuchsia-700/15 blur-3xl" />{children}</main>; }
function Topbar({ onHome }: { onHome: () => void }) { return <header className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><button onClick={onHome} className="flex items-center gap-3"><Mark /><span className="font-serif text-2xl tracking-tight">Veil</span></button><span className="hidden text-xs tracking-[.2em] text-violet-200/55 sm:block">CONNECTION, WITH INTENTION</span></header>; }
const Eyebrow = ({ children }: { children: React.ReactNode }) => <p className="text-[11px] font-semibold uppercase tracking-[.22em] text-violet-300">{children}</p>;

export default function VeilDemo() {
  const [stage, setStage] = useState<Stage>("landing"); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [visibleMessages, setVisibleMessages] = useState(0); const [mutual, setMutual] = useState(false);
  useEffect(() => { if (stage !== "date") return; const interval = window.setInterval(() => setVisibleMessages((n) => { if (n >= dateMessages.length) { window.clearInterval(interval); return n; } return n + 1; }), 850); return () => window.clearInterval(interval); }, [stage]);
  const begin = (demo = false) => { setAnswers(demo ? defaultAnswers : {}); setStep(0); setStage(demo ? "persona" : "onboarding"); };
  const question = questions[step]; const answer = answers[question?.id];
  return <Shell><Topbar onHome={() => setStage("landing")} />
    {stage === "landing" && <section className="relative mx-auto grid min-h-[calc(100vh-88px)] max-w-6xl items-center gap-12 px-6 pb-20 lg:grid-cols-[1.05fr_.95fr]"><div><Eyebrow>AN AI-ASSISTED DATING EXPERIENCE</Eyebrow><h1 className="mt-5 max-w-xl font-serif text-5xl leading-[.98] tracking-tight sm:text-7xl">Let your AI <em className="font-normal text-violet-300">break</em> the ice.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-white/65">Veil lets two profile-based AI personas share a low-stakes first conversation—then gives you both a thoughtful place to begin.</p><div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => begin()}>Create Your Veil <span className="ml-2">→</span></Button><Button secondary onClick={() => begin(true)}>Try Demo</Button></div><p className="mt-5 text-xs text-white/35">Private by design. You decide what your Veil knows.</p></div><div className="relative mx-auto w-full max-w-md"><div className="rounded-[2rem] border border-white/12 bg-white/[.06] p-5 shadow-2xl backdrop-blur"><div className="rounded-[1.5rem] bg-gradient-to-br from-violet-300/25 via-[#311a53] to-[#1a1029] p-7"><div className="flex items-center justify-between text-xs text-white/55"><span>THE VEIL ROOM</span><span>● LIVE</span></div><div className="mt-14 space-y-4"><div className="mr-8 rounded-2xl rounded-bl-sm bg-white/12 p-4 text-sm text-white/80">What kind of evening makes you lose track of time?</div><div className="ml-8 rounded-2xl rounded-br-sm bg-violet-300 p-4 text-sm text-[#190b2b]">One that leaves room for a lovely surprise.</div></div><div className="mt-12 flex items-center gap-3"><div className="size-9 rounded-full bg-fuchsia-300/40" /><div><p className="text-sm">Two stories, gently introduced</p><p className="text-xs text-white/50">No swiping required</p></div></div></div></div></div></section>}
    {stage === "onboarding" && <section className="relative mx-auto max-w-3xl px-6 py-10 sm:py-16"><div className="mb-10 flex items-center justify-between"><Eyebrow>Creating your Veil</Eyebrow><span className="text-sm text-white/45">{step + 1} / {questions.length}</span></div><div className="h-px overflow-hidden bg-white/10"><div className="h-full bg-gradient-to-r from-violet-400 to-fuchsia-300 transition-all" style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div><div className="mt-12"><Eyebrow>{question.eyebrow}</Eyebrow><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">{question.question}</h2><p className="mt-4 text-white/55">Choose the answer that feels most true today.</p><div className="mt-8 grid gap-3">{question.options.map((option) => <button key={option.label} onClick={() => setAnswers({ ...answers, [question.id]: option.label })} className={`flex items-center gap-4 rounded-2xl border p-5 text-left transition ${answer === option.label ? "border-violet-300 bg-violet-300/15" : "border-white/10 bg-white/[.035] hover:border-white/25"}`}><span className="grid size-10 place-items-center rounded-full bg-white/8 text-lg text-violet-200">{option.icon}</span><span><b className="block text-sm">{option.label}</b><span className="mt-1 block text-sm text-white/50">{option.detail}</span></span><span className={`ml-auto size-4 rounded-full border ${answer === option.label ? "border-violet-200 bg-violet-300 shadow-[0_0_15px_#c4b5fd]" : "border-white/25"}`} /></button>)}</div><div className="mt-9 flex justify-between"><Button secondary onClick={() => step === 0 ? setStage("landing") : setStep(step - 1)}>Back</Button><Button disabled={!answer} onClick={() => step === questions.length - 1 ? setStage("persona") : setStep(step + 1)}>Continue <span className="ml-2">→</span></Button></div></div></section>}
    {stage === "persona" && <section className="relative mx-auto grid min-h-[calc(100vh-88px)] max-w-5xl items-center gap-12 px-6 pb-16 md:grid-cols-2"><div><Eyebrow>Your introduction</Eyebrow><h2 className="mt-4 font-serif text-5xl sm:text-6xl">Meet your <em className="font-normal text-violet-300">Veil.</em></h2><p className="mt-6 max-w-md leading-7 text-white/60">Your Veil is a profile-based AI persona. It only represents information you choose to provide.</p><div className="mt-8"><Button onClick={() => setStage("match")}>Find My Match <span className="ml-2">→</span></Button></div></div><div className="rounded-[2rem] border border-violet-200/20 bg-gradient-to-br from-violet-300/20 to-white/[.03] p-7 shadow-2xl"><div className="flex items-start justify-between"><div className="grid size-16 place-items-center rounded-full bg-gradient-to-br from-violet-300 to-fuchsia-300 font-serif text-3xl text-[#1b0c2e]">V</div><span className="rounded-full border border-violet-200/25 px-3 py-1 text-[10px] tracking-widest text-violet-200">PROFILE-BASED</span></div><h3 className="mt-8 font-serif text-3xl">Your Veil</h3><p className="mt-2 text-sm leading-6 text-white/60">Thoughtful, open-hearted, and drawn to the good kind of detour.</p><div className="mt-8 flex flex-wrap gap-2">{Object.values(answers).slice(0, 5).map((item) => <span key={item} className="rounded-full bg-white/10 px-3 py-2 text-xs text-white/75">{item}</span>)}</div><div className="mt-10 border-t border-white/10 pt-5 text-xs leading-5 text-white/45">A reflection of what you shared—not a replacement for you.</div></div></section>}
    {stage === "match" && <section className="relative mx-auto max-w-4xl px-6 py-12 sm:py-20"><div className="text-center"><Eyebrow>A quiet possibility</Eyebrow><h2 className="mt-4 font-serif text-5xl sm:text-6xl">There&apos;s someone<br /><em className="font-normal text-violet-300">worth meeting.</em></h2><p className="mt-5 text-white/55">For now, we&apos;ll keep a little mystery.</p></div><div className="mx-auto mt-11 max-w-xl rounded-[2rem] border border-white/12 bg-white/[.055] p-6 sm:p-8"><div className="flex items-center gap-5"><div className="grid size-20 place-items-center rounded-full bg-gradient-to-br from-pink-200/80 to-violet-400/80 font-serif text-3xl text-[#281039]">M</div><div><h3 className="font-serif text-3xl">{match.name}, {match.age}</h3><p className="mt-1 text-sm text-white/50">A person with a story, not a score.</p></div></div><div className="mt-8 grid gap-6 border-t border-white/10 pt-6 sm:grid-cols-2"><div><Eyebrow>Drawn to</Eyebrow><div className="mt-3 flex flex-wrap gap-2">{match.interests.map((x) => <span className="rounded-full bg-white/8 px-3 py-1.5 text-xs" key={x}>{x}</span>)}</div></div><div><Eyebrow>Shared threads</Eyebrow><div className="mt-3 flex flex-wrap gap-2">{match.shared.map((x) => <span className="rounded-full bg-violet-300/15 px-3 py-1.5 text-xs text-violet-100" key={x}>{x}</span>)}</div></div></div><div className="mt-8 rounded-2xl bg-gradient-to-r from-violet-300/20 to-fuchsia-300/10 p-4"><p className="text-sm font-medium text-violet-100">Veil Signal <span className="ml-2 rounded-full bg-violet-200 px-2 py-1 text-xs text-[#260d3d]">Promising</span></p><p className="mt-2 text-xs leading-5 text-white/50">A gentle invitation to explore, not a scientific compatibility score.</p></div></div><div className="mt-8 text-center"><Button onClick={() => { setVisibleMessages(0); setStage("date"); }}>Send Our Veils on a Date <span className="ml-2">→</span></Button></div></section>}
    {stage === "date" && <section className="relative mx-auto flex min-h-[calc(100vh-88px)] max-w-3xl flex-col px-6 pb-12"><div className="pt-8 text-center"><Eyebrow>The Veil room</Eyebrow><h2 className="mt-3 font-serif text-4xl">A first conversation, gently held.</h2><p className="mt-3 text-xs text-white/45">AI-generated simulation based on user-provided profiles.</p></div><div className="my-8 flex flex-1 flex-col justify-end gap-4">{dateMessages.slice(0, visibleMessages).map(([name, text], i) => <div key={text} className={`flex animate-[fadeIn_.45s_ease-out] ${i % 2 ? "justify-end" : "justify-start"}`}><div className={`max-w-[82%] rounded-2xl p-4 text-sm leading-6 ${i % 2 ? "rounded-br-sm bg-violet-300 text-[#210d35]" : "rounded-bl-sm bg-white/10 text-white/80"}`}><p className={`mb-1 text-[10px] font-bold uppercase tracking-wider ${i % 2 ? "text-[#4f2671]" : "text-violet-200/70"}`}>{name}</p>{text}</div></div>)}</div>{visibleMessages >= dateMessages.length && <div className="rounded-2xl border border-violet-200/20 bg-violet-300/10 p-5 text-center animate-[fadeIn_.45s_ease-out]"><h3 className="font-serif text-2xl">Your Veils are back.</h3><p className="mt-2 text-sm text-white/55">They found a few threads worth holding onto.</p><div className="mt-5"><Button onClick={() => setStage("report")}>See What They Discovered <span className="ml-2">→</span></Button></div></div>}</section>}
    {stage === "report" && <section className="relative mx-auto max-w-5xl px-6 py-10 sm:py-16"><div className="text-center"><Eyebrow>Compatibility exploration</Eyebrow><h2 className="mt-3 font-serif text-5xl">Worth <em className="font-normal text-violet-300">Exploring.</em></h2><p className="mt-4 text-white/55">Not a verdict. A few inviting places to begin.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2"><ReportCard title="Areas of alignment" items={["Both prefer meaningful conversation over performative small talk.", "Food, neighborhood wandering, and unplanned discovery feel like shared joy.", "You each value warmth paired with clear communication."]} /><ReportCard title="Differences worth discussing" items={["Mara may lean a little more spontaneous; you appreciate some gentle structure.", "Your social rhythms could be different—an easy early conversation to have."]} /><ReportCard title="Conversation starters" items={["What is the best tiny restaurant you’ve found lately?", "Which creative hobby would you happily teach someone?", "What does a really good weekend look like to you?"]} /><ReportCard title="Explore on a real first date" items={["How each of you makes room for connection in a busy week.", "What curiosity and care look like when things are not effortless."]} /></div><p className="mx-auto mt-8 max-w-3xl text-center text-xs leading-6 text-white/42">This report is an AI-generated exploration based on information provided by both users. Real-world chemistry can only be discovered by the people themselves.</p><div className="mt-8 text-center"><Button onClick={() => setStage("reveal")}>Lift the Veil <span className="ml-2">→</span></Button></div></section>}
    {stage === "reveal" && <section className="relative mx-auto flex min-h-[calc(100vh-88px)] max-w-3xl items-center justify-center px-6 pb-16 text-center">{!mutual ? <div><Eyebrow>The moment of choice</Eyebrow><h2 className="mt-5 font-serif text-5xl leading-tight sm:text-6xl">Would you like to meet the person behind the Veil?</h2><p className="mx-auto mt-6 max-w-lg text-white/60">There&apos;s no right answer. A good connection starts with choosing what feels right to you.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Button secondary onClick={() => setStage("landing")}>Stay Veiled</Button><Button onClick={() => setMutual(true)}>I&apos;m Curious <span className="ml-2">→</span></Button></div></div> : <div className="animate-[fadeIn_.6s_ease-out]"><div className="mx-auto grid size-20 place-items-center rounded-full bg-gradient-to-br from-violet-300 to-fuchsia-300 font-serif text-4xl text-[#260d3d]">M</div><Eyebrow><span className="mt-8 block">The signal returned</span></Eyebrow><h2 className="mt-4 font-serif text-6xl text-violet-200 sm:text-7xl">It&apos;s mutual.</h2><p className="mt-5 font-serif text-3xl">Meet Mara, 29.</p><p className="mx-auto mt-4 max-w-md text-white/60">Ceramicist, film photographer, believer in long dinners and the right kind of detour.</p><div className="mt-12 border-t border-white/10 pt-7 font-serif text-2xl text-white/80">The Veil lifts here. The rest is yours.</div><div className="mt-8"><Button secondary onClick={() => setStage("landing")}>Return home</Button></div></div>}</section>}
  </Shell>;
}

function ReportCard({ title, items }: { title: string; items: string[] }) { return <article className="rounded-2xl border border-white/10 bg-white/[.045] p-6"><Eyebrow>{title}</Eyebrow><ul className="mt-4 space-y-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-white/68"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-violet-300" />{item}</li>)}</ul></article>; }
